# shell:
  # program: /bin/zsh
  # args:
  # - --logins
  #   - -c
  #   - exec tmux && zsh

font:
  size: 12
  normal:
    family: JetBrains Mono Nerd Font
    # family: JetBrains Mono
    style: Regular

  # The bold font face
  bold:
    # family: JetBrains Mono NL
    family: JetBrains Mono Nerd Font
    style: Bold

  # The italic font face
  italic:
    # family: JetBrains Mono NL
    family: JetBrains Mono Nerd Font
    style: Italic

# env:
#   LC_ALL: en_US.UTF-8
#   LANG: en_US.UTF-8
